openapi: 3.0.3
info:
  title: Blockchain Public Address
  description: |-
    Allows to manage Blockchain Public Address associated with a mobile phone number.

    # Relevant Definitions and concepts
    - **NaaS**: *Network-as-a-Service* model where Telco Operator Network resources are exposed to third parties through APIs. In this particular API, Blockchain Public Address is managed following this model.
    - **Blockchain Public Address**: Unique string of code used by individuals to receive or request payments in cryptocurrency.
    
    # API Functionality
    This API allows to manage a Blockchain Public Address associated with a mobile phone number, i.e.: to retrieve the Blockchain Public Address(es) and to bind/unbind a Blockchain Public Address.

    # Resources and Operations overview
    This API provides three endpoints:
     - **Endpoint to retrieve the Blockchain Public Address(es) associated with a mobile phone number sent as input**. The Blockchain Public Address is information made available by the user, in association to their mobile phone number. Then, this endpoint may be accessed in 2-legged or in 3-legged mode. Even in 3-legged mode, the mobile phone number included as input field does not need to belong to the sub (user_id) for which the Access Token is issued. This will enable a user to ask for the Blockchain Public Address(es) of any mobile phone number, in order to perform a transaction with one of the available ones (send or request).
     Notice that the mobile phone number used as input may even not belong to the same Telco Operator exposing the API. It is expected a communication between Telco Operators to resolve the Blockchain Public Address(es). For example a Telco Operator will receive the request, identify the Telco Operator which owns the mobile phone number, and forward the request using a 2-legged approach to contact the other Telco Operator.
     - **Endpoint to associate a mobile phone number with a Blockchain Public Address**. It does not matter if the mobile phone number is already bound to a Blockchain Public Address, as this operation adds a new Blockchain Public Address. This operation is intended to be used with a 3-legged Access Token, and the indicated mobile phone number must belong to the sub in the Access Token; this is because only the user of the mobile phone number must be able to perform a bind. As a consequence, this operation will only work with mobile phone numbers of the Telco Operator exposing the API.
     - **Endpoint to remove the association of a mobile phone number with a Blockchain Public Address**. This operation is intended to be used with a 3-legged Access Token; this is because only the user of the mobile phone number must be able to perform an unbind. Note: Due to this, the API Server must validate that the `id` included in the request refers to a bind for a mobile phone number belonging to the sub in the Access Token and, when identifier_bound_scopes are used, validate that the `id` included in the request refers to a bind for a mobile phone number appearing in the list of identifier_bound_scopes for the scope protecting this endpoint. As a consequence, this operation will only work with mobile phone numbers of the Telco Operator exposing the API.

    # Further Info and Support

    (FAQs will be added in a later version of the documentation)
  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.2.0-wip
externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: blockchain-public-address/v0
        description: Base path for the Blockchain Public Address API
tags:
  - name: Blockchain Public Address
    description: API operations to manage Blockchain Public Addresses
paths:
  /blockchain-public-addresses:
    get:
      tags:
        - Blockchain Public Address
      summary: Retrieves Blockchain Public Address associated with a mobile phone number.
      description:
        Retrieves Blockchain Public Address associated with a mobile phone number. This operation can be accessed in 3-legged and in 2-legged, notice that the mobile phone number used as input need not be related with the user or mobile phone number to which the Access
        Token is associated; this is because the operation is intended to be used to manage Blockchain Public Address of any mobile phone number, in order to perform send or request crypto operations.
      operationId: retrieveBlockchainPublicAddress
      security:
        - openId:
          - blockchain-public-address:read
      parameters:
        - $ref: "#/components/parameters/PhoneNumber"
        - $ref: "#/components/parameters/x-correlator"
      responses:
        "200":
          description: OK
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                type: array
                description: Array of Blockchain Public Addresses bound to the mobile phone number
                items:
                  $ref: "#/components/schemas/BlockchainPublicAddressResponse"
              examples:
                RetrieveBlockchainPublicAddressResponse200Example:
                  value:
                    - id: "90c626ce-5284-4a84-b85e-46e0ee3d0434"
                      blockchainPublicAddress: "0x71C7656EC7ab88b098dafB451B2314C5f6d8932A"
                      blockchainNetworkId: "evm:1"
                      currency:
                        - ETH
                    - id: "5c179f50-db37-4d23-87e3-6f10c991899f"
                      blockchainPublicAddress: "0x329CdCAAC31c934fe32322b111bE8fBd30b4FFA9"
                      blockchainNetworkId: "evm:137"
                      currency:
                        - WETH
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
    post:
      tags:
        - Blockchain Public Address
      summary: Binds Blockchain Public Address to a mobile phone number
      description:
        Binds Blockchain Public Address to a mobile phone number. If the mobile phone number is already bound to a Blockchain Public Address, this operation will add a new bound Blockchain Public Address to the mobile phone number. This operation is intended to be used
        with a 3-legged Access Token, and the indicated mobile phone number must belong to the user identified by its `sub` in the Access Token; this is because only the user of the mobile phone number must be able to perform the bind.
      operationId: bindBlockchainPublicAddress
      security:
        - openId:
          - blockchain-public-address:create
      parameters:
        - $ref: "#/components/parameters/x-correlator"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BindBlockchainPublicAddressRequest"
      responses:
        "201":
          description: Created
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BindBlockchainPublicAddressResponse"
              examples:
                BindBlockchainPublicAddressResponse201Example:
                  value:
                    id: "90c626ce-5284-4a84-b85e-46e0ee3d0434"
        "400":
          $ref: "#/components/responses/InvalidArgumentForBlockchain400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/PermissionDeniedForBlockchain403"
        "404":
          $ref: "#/components/responses/Generic404"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /blockchain-public-addresses/{id}:
    delete:
      tags:
        - Blockchain Public Address
      summary: Unbinds Blockchain Public Address association to a mobile phone number
      description: |-
        Unbinds Blockchain Public Address to a mobile phone number. This operation is intended to be used with a 3-legged Access Token; this is because only the user of the mobile phone number must be able to perform the unbind.
        Note: Due to this, the API Server must validate that the `id` included in the request refers to a bind for a mobile phone number belonging to the user identified by its `sub` in the Access Token and, when identifier_bound_scopes are used, validate that the `id` included in the request refers to a bind for a mobile phone number appearing in the list of identifier_bound_scopes for the scope protecting this endpoint.
      operationId: deleteBlockchainPublicAddress
      security:
        - openId:
          - blockchain-public-address:delete
      parameters:
        - $ref: "#/components/parameters/Id"
        - $ref: "#/components/parameters/x-correlator"
      responses:
        "204":
          description: No Content
          headers:
            x-correlator:
              $ref: "#/components/headers/x-correlator"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "429":
          $ref: "#/components/responses/Generic429"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
components:
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
    Id:
      name: id
      in: path
      description: Unique identifier given to the bind relationship of a mobile `phoneNumber` with a Blockchain Public Address.
      required: true
      schema:
        type: string
    PhoneNumber:
      name: phoneNumber
      in: query
      description: A mobile phone number belonging to the user. In order to be globally unique it has to be formatted in international format, according to E.164 standard, optionally prefixed with '+'.
      required: true
      schema:
        type: string
  schemas:
    BindBlockchainPublicAddressRequest:
      type: object
      description: Payload to request the Bind of the Blockchain Public Adddress
      required:
        - phoneNumber
        - blockchainPublicAddress
        - blockchainNetworkId
      properties:
        phoneNumber:
          type: string
          description: Mobile phone number to which the Blockchain Public Address will be bound. In order to be globally unique it has to be formatted in international format, according to E.164 standard, optionally prefixed with '+'.
        blockchainPublicAddress:
          type: string
          description: User's Blockchain Public Address to bind to the mobile `phoneNumber`
        blockchainNetworkId:
          type: string
          pattern: ^[a-zA-Z0-9]+:?[a-zA-Z0-9]+$
          description: |-
            Identifier (i.e. name/type) of the blockchain whose address value is provided within `blockchainPublicAddress`. The model proposed aims to provide an extensible way to list/identify every blockchain ecosystems.
            Proposed format is: `<L1_Ecosystem>:<sub_id>`, where:
            
            - `<L1_Ecosystem>`: Represents a Layer 1 Blockchain Ecosystem (e.g. ethereum, bitcoin,...)
            - `<sub_id>`: Represents subsequents L2 and Testnet Blockchain Ecosystems, whenever they apply (e.g. bitcoin is a monolithic blockchain so as this concept does not apply)

            So far, in the scope of v0.2 of this specification, the following `<L1_Ecosystem>` values are covered:
            - `evm`: Representing a common L1 Layer concept for EVM-based networks. Within this Ecosystem, `<sub_id>` concept is required and matches the value of chainId as per [EVM ChainId](https://chainid.network/). For instance:
              - `ethereum` blockchain would be identified by `evm:1` value (i.e. ethereum mainnet).
              - `polygon` blockhain would be identified by `evm:137` value (i.e. polygon mainnet).
              - `celo` blockchain would be identified by `evm:42220` value (i.e. celo mainnet).
            - `bitcoin`: Representing Bitcoin L1 blockchain. No `<sub_id>` concept applies for this L1 Ecosystem
            - `solana`: Representing Solana L1 blockchain. No `<sub_id>` concept applies for this L1 Ecosystem
            - `cardano`: Representing Cardano L1 blockchain. No `<sub_id>` concept applies for this L1 Ecosystem
        currency:
          type: array
          description: List of currencies for the blockchain. Optional field (generally not needed), only indicated when there are business needs to set one or a list on currencies supported.
          minItems: 0
          items: 
            type: string
      example:
        phoneNumber: "+346789990012"
        blockchainPublicAddress: "0x71C7656EC7ab88b098dafB451B2314C5f6d8932A"
        blockchainNetworkId: "evm:1"
        currency:
          - ETH
    BindBlockchainPublicAddressResponse:
      type: object
      description: Bind Blockchain Public Address response
      required:
        - id
      properties:
        id:
          type: string
          description: Unique identifier given to the bind relationship of a mobile `phoneNumber` with a Blockchain Public Address.
    BlockchainPublicAddressResponse:
      type: object
      description: Blockchain Public Address response
      required:
        - id
        - blockchainPublicAddress
        - blockchainNetworkId
      properties:
        id:
          type: string
          description: Unique identifier given to the bind relationship of a mobile `phoneNumber` with a Blockchain Public Address.
        blockchainPublicAddress:
          type: string
          description: User's Blockchain Public Address
        blockchainNetworkId:
          type: string
          description: |-
            Identifier (i.e. name/type) of the blockchain whose address value is provided within `blockchainPublicAddress`. The model proposed aims to provide an extensible way to list/identify every blockchain ecosystems.
            Proposed format is: `<L1_Ecosystem>:<sub_id>`, where:
            
            - `<L1_Ecosystem>`: Represents a Layer 1 Blockchain Ecosystem (e.g. ethereum, bitcoin,...)
            - `<sub_id>`: Represents subsequents L2 and Testnet Blockchain Ecosystems, whenever they apply (e.g. bitcoin is a monolithic blockchain so as this concept does not apply)

            So far, in the scope of v0.2 of this specification, the following `<L1_Ecosystem>` values are covered:
            - `evm`: Representing a common L1 Layer concept for EVM-based networks. Within this Ecosystem, `<sub_id>` concept is required and matches the value of chainId as per [EVM ChainId](https://chainid.network/). For instance:
              - `ethereum` blockchain would be identified by `evm:1` value (i.e. ethereum mainnet).
              - `polygon` blockhain would be identified by `evm:137` value (i.e. polygon mainnet).
              - `celo` blockchain would be identified by `evm:42220` value (i.e. polygon mainnet).
            - `bitcoin`: Representing Bitcoin L1 blockchain. No `<sub_id>` concept applies for this L1 Ecosystem
            - `solana`: Representing Solana L1 blockchain. No `<sub_id>` concept applies for this L1 Ecosystem
            - `cardano`: Representing Cardano L1 blockchain. No `<sub_id>` concept applies for this L1 Ecosystem
        currency:
          type: array
          description: List of currencies for the blockchain. Optional field (generally not needed), only indicated when there are business needs to set one or a list on currencies supported.
          minItems: 0
          items: 
            type: string
    ErrorInfo:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code returned along with this error response
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
      required:
        - status
        - code
        - message
  responses:
    InvalidArgumentForBlockchain400:
      description: |
        Problem with the client request.
        In addition to regular scenario of INVALID_ARGUMENT, other exceptions may exist.
         - Indicated blockchainNetworkId is not valid ("code": "BLOCKCHAIN_PUBLIC_ADDRESS.INVALID_BLOCKCHAIN_NETWORK_ID","message": "Indicated blockchainNetworkId is not valid")
         - Indicated currency is not valid for the Blockchain ("code": "BLOCKCHAIN_PUBLIC_ADDRESS.INVALID_CURRENCY","message": "Indicated currency is not found")
         - Currency indication is required ("code": "BLOCKCHAIN_PUBLIC_ADDRESS.CURRENCY_REQUIRED","message": "One currency is required")
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            InvalidArgument:
              value:
                code: INVALID_ARGUMENT
                message: Client specified an invalid argument, request body or query param
            InvalidCurrencyForBlockchain:
              value:
                code: BLOCKCHAIN_PUBLIC_ADDRESS.INVALID_CURRENCY
                message: Indicated currency is not found
    PermissionDeniedForBlockchain403:
      description: |
        Forbidden.
        In addition to regular scenario of PERMISSION_DENIED, other exceptions may exist.
         - Blockchain identifier not allowed by business rules ("code": "BLOCKCHAIN_PUBLIC_ADDRESS.BLOCKCHAIN_NETWORK_IDENTIFIER_NOT_ALLOWED","message": "Indicated blockchainNetworkId is not allowed by business rules")
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          examples:
            PermissionDenied:
              value:
                code: PERMISSION_DENIED
                message: "Operation not allowed: ..."
            NotAllowedBlockchainNetworkId:
              value:
                code: BLOCKCHAIN_PUBLIC_ADDRESS.BLOCKCHAIN_NETWORK_IDENTIFIER_NOT_ALLOWED
                message: Indicated blockchainNetworkId is not allowed by business rules
    Generic400:
      description: Problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 400
            code: INVALID_ARGUMENT
            message: Client specified an invalid argument, request body or query param
    Generic401:
      description: Authentication problem with the client request
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 401
            code: UNAUTHENTICATED
            message: Request not authenticated due to missing, invalid, or expired credentials
    Generic403:
      description: Forbidden
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 403
            code: PERMISSION_DENIED
            message: "Operation not allowed: ..."
    Generic404:
      description: Not found
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 404
            code: NOT_FOUND
            message: The specified resource is not found
    Generic429:
      description: Too Many Requests
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 429
            code: TOO_MANY_REQUESTS
            message: Either out of resource quota or reaching rate limiting
    Generic500:
      description: Server error
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 500
            code: INTERNAL
            message: Server error
    Generic503:
      description: Service unavailable
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 503
            code: UNAVAILABLE
            message: Service unavailable
    Generic504:
      description: Request time exceeded. If it happens repeatedly, consider reducing the request complexity
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 504
            code: TIMEOUT
            message: Request timeout exceeded
